name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Build and Push to Docker Hub Action
        uses: rtvu/build-and-push-to-docker-hub-action@v2.1.0
        with:
          token: ${{ secrets.DOCKER_TOKEN }}
          username: ${{ secrets.DOCKER_USERNAME }}
          

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: ssh-scp-ssh-pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.EC2_IP }}
          user: ${{ secrets.DOCKER_USERNAME }}
          key:  ${{ secrets.SSH_PRIVATE_KEY }}   

      - name: Deploy to Minikube
        run: |
            kubectl apply -f ~/kubernetes/secret.yaml
            kubectl apply -f ~/kubernetes/configmap.yaml
            kubectl apply -f ~/kubernetes/service.yaml
            kubectl apply -f ~/kubernetes/deployment.yaml
            EOF
