name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.6.1
        with:
          context: .
          push: true
          tags: bankdoo/kctest-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      # - name: Setup SSH Action
      #   uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
      #   with:
      #     SSHKEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Minikube
        run: 
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > kckey_rsa.pem
          chmod 400 kckey_rsa.pem
          scp -r -i "kckey_rsa.pem" ./kubernetes/ ubuntu@${{ secrets.EC2_IP }}:~/kubernetes/
          ssh -i "kckey_rsa.pem" ubuntu@${{ secrets.EC2_IP }}
          kubectl apply -f ~/kubernetes/secret.yaml
          kubectl apply -f ~/kubernetes/configmap.yaml
          kubectl apply -f ~/kubernetes/service.yaml
          kubectl apply -f ~/kubernetes/deployment.yaml
          EOF
